""" Constants module for discord.py bot """

import discord
from logging import INFO, DEBUG, ERROR, WARNING, CRITICAL

# Config stuff
VALID_LOG_LEVELS = {"normal": INFO, "verbose": DEBUG, "errors": ERROR, "warnings": WARNING, "critical": CRITICAL}
VALID_ACTIVITY_TYPES = {"playing": discord.ActivityType.playing, "watching": discord.ActivityType.watching, "listening": discord.ActivityType.listening}
VALID_STATUSES = {"online": discord.Status.online, "idle": discord.Status.idle, "do_not_disturb": discord.Status.do_not_disturb, "invisible": discord.Status.invisible}

# Moderation stuff
MAX_CHANNEL_NAME_LENGTH = 100
MAX_TOPIC_LENGTH = 1024
MAX_FORUM_TOPIC_LENGTH = 4096
MAX_SLOWMODE = 21600 
MAX_BITRATE = 96000 # default, changes depending on guild
MAX_STAGE_BITRATE = 64000
MAX_USER_LIMIT = 99
MAX_ANNOUNCEMENT_LENGTH_LIMIT = 2000
MAX_PURGE_LIMIT = 500

# Voice stuff
MAX_USER_WAIT_TIME_AFTER_CHANNEL_MOVE = 10
MAX_GUILD_CLEANUP_WAIT_TIME = 10
GREET_TIMEOUT_SECONDS = 10
PLAYBACK_END_GRACE_PERIOD = 1
MAX_STREAM_REFRESH_RETRY_COUNT = 2
MAX_RETRY_COUNT = 3
CRASH_RECOVERY_TIME_WINDOW = 10
FFMPEG_RECONNECT_TIMEOUT_SECONDS = 10
FFMPEG_READ_WRITE_TIMEOUT_MICROSECONDS = 7000000

# HTTP ClientSession stuff
HTTP_CLIENT_SESSION_TIMEOUT = 5
IS_STREAM_URL_ALIVE_REQUEST_HEADERS = {
    "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36"
}
NEKOS_MOE_REQUEST_HEADERS = {
    "User-Agent": "MusicBot.py/2.0"
}
NEKOS_MOE_API_VERSION = "v1"
NEKOS_MOE_BASE_URL = "https://nekos.moe"
NEKOS_MOE_ENDPOINT = NEKOS_MOE_BASE_URL + f"/api/{NEKOS_MOE_API_VERSION}"
NEKOS_MOE_RANDOM_ENDPOINT = NEKOS_MOE_ENDPOINT + "/random/image"
NEKOS_MOE_IMAGE = NEKOS_MOE_BASE_URL + "/image"

# Bot config stuff
MAX_IO_SYNC_WAIT_TIME = 20
MAX_GUILD_COUNT_BEFORE_SHARDING_REQUIRED = 2500
MAX_FETCH_CALLS = 50

# Filter stuff
RAW_FILTER_TO_VISUAL_TEXT = {
    "uploader": "Author",
    "min_duration": "Minimum duration",
    "max_duration": "Maximum duration",
    "source_website": "Website"
}
NEED_TIME_FORMATTING_TO_MINUTES_FILTERS = ["min_duration", "max_duration"]

# Cooldowns
COOLDOWNS = {
    "PING_COMMAND_COOLDOWN": 5.0,
    "HELP_COMMAND_COOLDOWN": 5.0,
    "JOIN_COMMAND_COOLDOWN": 5.0,
    "LEAVE_COMMAND_COOLDOWN": 5.0,
    "ADD_COMMAND_COOLDOWN": 20.0,
    "PLAYNOW_COMMAND_COOLDOWN": 20.0,
    "SKIP_COMMAND_COOLDOWN": 10.0,
    "NEXTINFO_COMMAND_COOLDOWN": 5.0,
    "PREVIOUSINFO_COMMAND_COOLDOWN": 5.0,
    "PAUSE_COMMAND_COOLDOWN": 10.0,
    "RESUME_COMMAND_COOLDOWN": 10.0,
    "STOP_COMMAND_COOLDOWN": 10.0,
    "RESTART_COMMAND_COOLDOWN": 10.0,
    "SELECT_COMMAND_COOLDOWN": 10.0,
    "SELECT_RANDOM_COMMAND_COOLDOWN": 10.0,
    "REPLACE_COMMAND_COOLDOWN": 20.0,
    "LOOP_COMMAND_COOLDOWN": 7.0,
    "RANDOM_COMMAND_COOLDOWN": 7.0,
    "QUEUELOOP_COMMAND_COOLDOWN": 7.0,
    "CLEAR_COMMAND_COOLDOWN": 10.0,
    "REMOVE_COMMAND_COOLDOWN": 10.0,
    "REPOSITION_COMMAND_COOLDOWN": 10.0,
    "SHUFFLE_COMMAND_COOLDOWN": 10.0,
    "SEEK_COMMAND_COOLDOWN": 10.0,
    "REWIND_COMMAND_COOLDOWN": 10.0,
    "FORWARD_COMMAND_COOLDOWN": 10.0,
    "QUEUE_COMMAND_COOLDOWN": 5.0,
    "HISTORY_COMMAND_COOLDOWN": 5.0,
    "EXTRACTION_PROGRESS_COMMAND_COOLDOWN": 5.0,
    "STOP_EXTRACTION_COMMAND_COOLDOWN": 7.0,
    "EPOCH_COMMAND_COOLDOWN": 5.0,
    "YOINK_COMMAND_COOLDOWN": 7.0,
    "FILTER_COMMAND_COOLDOWN": 10.0,
    "CLEAR_FILTERS_COMMAND_COOLDOWN": 10.0,
    "VIEW_FILTERS_COMMAND_COOLDOWN": 5.0,
    "NOWPLAYING_COMMAND_COOLDOWN": 5.0,
    "ALLOW_GREETINGS_COMMAND_COOLDOWN": 7.0,
    "ALLOW_VOICE_STATUS_EDIT_COMMAND_COOLDOWN": 7.0,
    "PLAYLIST_VIEW_COMMAND_COOLDOWN": 5.0,
    "PLAYLIST_SAVE_QUEUE_COMMAND_COOLDOWN": 10.0,
    "PLAYLIST_SAVE_HISTORY_COMMAND_COOLDOWN": 10.0,
    "PLAYLIST_SAVE_CURRENT_TRACK_COMMAND_COOLDOWN": 10.0,
    "PLAYLIST_SELECT_COMMAND_COOLDOWN": 30.0,
    "PLAYLIST_CREATE_COMMAND_COOLDOWN": 10.0,
    "PLAYLIST_DELETE_COMMAND_COOLDOWN": 10.0,
    "PLAYLIST_REMOVE_COMMAND_COOLDOWN": 10.0,
    "PLAYLIST_RESET_COMMAND_COOLDOWN": 60.0,
    "PLAYLIST_RENAME_COMMAND_COOLDOWN": 10.0,
    "PLAYLIST_REPLACE_COMMAND_COOLDOWN": 20.0,
    "PLAYLIST_REPOSITION_COMMAND_COOLDOWN": 10.0,
    "PLAYLIST_ADD_COMMAND_COOLDOWN": 25.0,
    "PLAYLIST_COPY_COMMAND_COOLDOWN": 10.0,
    "PLAYLIST_MOVE_COMMAND_COOLDOWN": 10.0,
    "PLAYLIST_COPY_TRACKS_COMMAND_COOLDOWN": 10.0,
    "PLAYLIST_MOVE_TRACKS_COMMAND_COOLDOWN": 10.0,
    "PLAYLIST_FETCH_TRACKS_COMMAND_COOLDOWN": 25.0,
    "PLAYLIST_FETCH_RANDOM_TRACKS_COMMAND_COOLDOWN": 25.0,
    "PLAYLIST_IMPORT_COMMAND_COOLDOWN": 30.0,
    "PLAYLIST_RENAME_TRACKS_COMMAND_COOLDOWN": 10.0,
    "PLAYLIST_GET_SAVED_COMMAND_COOLDOWN": 5.0,
    "ROLE_SET_COMMAND_COOLDOWN": 15.0,
    "ROLE_GET_COMMAND_COOLDOWN": 5.0,
    "ROLE_REMOVE_COMMAND_COOLDOWN": 15.0,
    "ROLE_RESET_COMMAND_COOLDOWN": 60.0,
    "PURGE_CHANNEL_COMMAND_COOLDOWN": 45.0,
    "KICK_COMMAND_COOLDOWN": 10.0,
    "BAN_COMMAND_COOLDOWN": 10.0,
    "UNBAN_COMMAND_COOLDOWN": 10.0,
    "TIMEOUT_COMMAND_COOLDOWN": 10.0,
    "REMOVE_TIMEOUT_COMMAND_COOLDOWN": 10.0,
    "ADD_ROLE_COMMAND_COOLDOWN": 10.0,
    "REMOVE_ROLE_COMMAND_COOLDOWN": 10.0,
    "DELETE_CHANNEL_COMMAND_COOLDOWN": 10.0,
    "CREATE_CHANNEL_COMMAND_COOLDOWN": 20.0,
    "CHANGE_SLOWMODE_COMMAND_COOLDOWN": 15.0,
    "ANNOUNCE_MESSAGE_COMMAND_COOLDOWN": 15.0,
    "MOVE_USER_COMMAND_COOLDOWN": 10.0,
    "VC_KICK_COMMAND_COOLDOWN": 10.0,
    "VC_MUTE_COMMAND_COOLDOWN": 10.0,
    "GET_CATGIRL_COMMAND_COOLDOWN": 10.0
}